language: node_js
node_js:
  - "8"
cache: yarn
script:
  - yarn test
  - yarn gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/react-color-wheel
  on:
    branch: master
